name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn publish --new-version ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
